Some changes.
Changes:
- Attempted to make the placeholder plant texture transparent. Looked up how to do it in Paint(as thats where I made the texture) to no avail. Also tried in Photoshop which I very much could have done so there but in the end stopped so I could work on something more prioritized.

- Made another script(Player Behaviour)
I've kept an older version of the code for a NPC use idea I have, that being NPCs that will attack you and other NPCs that will ignore you.

Add at home later:
Excel:
- error CS1525: Invalid expression term '-=' <- Accidentally added two equal signs.
- error CS0246: The type or namespace name 'GameBehavior' could not be found (are you missing a using directive or an assembly reference?) <-